### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by marcelgcom** [schmich/deckstrings#1]
decode() returns the correct number of cards but IDs are all different than what is expected.

**Comment by schmich** [comment]
What deckstring are you decoding? What IDs are you expecting?

If it's a bug, I should be able to fix it quickly.

**Comment by marcelgcom** [comment]
For example
> AAECAZICCPIF+Az5DK6rAuC7ApS9AsnHApnTAgtAX/4BxAbkCLS7Asu8As+8At2+AqDNAofOAgA=

[This is decoded by Hearthpwn](https://www.hearthpwn.com/deckbuilder/druid#42:1;73:1;120:2;282:2;396:1;548:2;620:2;633:2;35208:1;49628:1;49703:2;49706:1;49708:2;49714:2;49718:2;55533:1;62841:2;62879:2;62904:1)

This is decoded by deckstrings:
{2 [274] [[64 2] [95 2] [254 2] [754 1] [836 2] [1124 2] [1656 1] [1657 1] [38318 1] [40372 2] [40416 1] [40523 2] [40527 2] [40596 1] [40797 2] [41929 1] [42656 2] [42759 2] [43417 1]]}

**Comment by schmich** [comment]
I don't believe this is a bug. The output you're seeing from the deckstrings library is correct. I believe Hearthpwn is using its own internal IDs in their URLs.

If you visit https://develop.battle.net (to avoid CORS issues), open a JS console, then run the following, you can see how the official Hearthstone API decodes this deckstring. You'll see that the sorted card DBF IDs match the deckstrings decoding.

```javascript
(async () => {
	let deckstring = 'AAECAZICCPIF+Az5DK6rAuC7ApS9AsnHApnTAgtAX/4BxAbkCLS7Asu8As+8At2+AqDNAofOAgA=';
	let response = await fetch(`https://api.blizzard.com/hearthstone/deck/${encodeURIComponent(deckstring)}?region=us&locale=en_US`, { headers: new Headers([['Authorization', 'Bearer USs6q5AJWPytId5lOKwt4n2963cAJBQI1Y']]) });
	let { cards } = await response.json();
	let ids = cards.map(c => c.id).sort((p, q) => p - q);
	console.log(ids);
})();
```
Output:
```
[64, 64, 95, 95, 254, 254, 754, 836, 836, 1124, 1124, 1656, 1657, 38318, 40372, 40372, 40416, 40523, 40523, 40527, 40527, 40596, 40797, 40797, 41929, 42656, 42656, 42759, 42759, 43417]
```

Also, to further the point, I created a deck on Hearthpwn with just 2 Wraths: https://www.hearthpwn.com/deckbuilder/druid#633:2.

If you look at the [HearthstoneJSON dataset](https://api.hearthstonejson.com/v1/33157/enUS/cards.json), you'll notice there is no card with DBF ID 633 (Wrath's DBF ID is 836). My guess is that Hearthpwn has their own internal IDs for each card.

```
{
  "artist": "Raymond Swanland",
  "cardClass": "DRUID",
  "collectible": true,
  "cost": 2,
  "dbfId": 836,
  "flavor": "The talk around the Ratchet Inn is that this card is too good and should be a Legendary.",
  "id": "EX1_154",
  "mechanics": [
    "CHOOSE_ONE"
  ],
  "name": "Wrath",
  "playRequirements": {
    "REQ_MINION_TARGET": 0,
    "REQ_TARGET_TO_PLAY": 0
  },
  "rarity": "COMMON",
  "set": "EXPERT1",
  "text": "<b>Choose One -</b>\nDeal $3 damage to a minion; or $1 damage\nand draw a card.",
  "type": "SPELL"
}
```

**Comment by marcelgcom** [comment]
> I believe Hearthpwn is using its own internal IDs in their URLs.
Ah, I've totally missed this. Thank you for looking into it.
